### ISSUE TITLE
想咨询您学习gradle的途径

### ISSUE THREAD

**Issue by JuneLeo** [SmartDengg/asm-clickdebounce#2]
最近也在学习gradle方面的知识，从appplugin入手看源码，相当的困难，网上也找过文章，但是效果不是很好，想咨询您gradle的一些书籍和文章，谢谢您了！
7月份去贝壳面试过，面试官说你们那边的热更新是通过部门打包jar包下发的，也想了解下这方面的知识！

**Comment by SmartDengg** [comment]
看源码只能是现学现卖，并不能通篇系统的了解gradle，建议从官方的[用户手册](https://docs.gradle.org/current/userguide/userguide.html)学起，然后再学习一些优秀的开源项目。
关于更新，恕不能透露太多，建议把流行的插件化/热修复都调研一遍，其中的奥秘也就能理解了。
“学而不思则罔，思而不学则殆”，多思考，多动手，任何问题都会迎刃而解。
